### ISSUE TITLE
Quasar Dispatch Support

### ISSUE THREAD

**Issue by georgino-ccrp** [Arius-Development/ars_ambulancejob#2]
hi, i wanted to ask if somebody know how to add qs-dispatch export.. or if you would do that in the next update

**Comment by Nico-du-34** [comment]
Hi you have to go to this file 'client\paramedic.lua' on line 139 and you add the qs-dispatch export below
![image](https://github.com/Arius-Scripts/ars_ambulancejob/assets/140889974/96454f2d-b676-41a9-b834-24a69ef1937b)
![image](https://github.com/Arius-Scripts/ars_ambulancejob/assets/140889974/43961a41-8544-4efb-80e0-70e1bc82edab)
