### ISSUE TITLE
qs-inventory compatibility

### ISSUE THREAD

**Issue by djkriss0804** [Arius-Development/ars_ambulancejob#8]
Hello, maybe I'm writing in the wrong place but I hope you will forgive me. 
In general, I struggled with adapting this script to qs-inventory, but I failed and I have a question: is there a possible version or is it planned to add compatibility for qs-inventory?

**Comment by Arius-Scripts** [comment]
i will be adding compatibility to other inventory in near future

**Comment by Arius-Scripts** [comment]
i will be adding compatibility to other inventory in near future

**Comment by Arius-Scripts** [comment]
i will be adding compatibility to other inventory in near future
